# Generated by Django 4.2.2 on 2023-10-18 17:52

from django.db import migrations, models

import catalog.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=catalog.models.category_image_directory_path,
                verbose_name="image",
            ),
        ),
    ]
