# Generated by Django 4.2.2 on 2023-10-21 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_category_image"),
        ("catalog", "0002_review_is_valid"),
    ]

    operations = []
