# Generated by Django 4.2.2 on 2023-11-07 16:12

from django.db import migrations, models

import catalog.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_banner_options_alter_productimage_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="Название"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, db_index=True, verbose_name="Описание"
                    ),
                ),
                (
                    "promocode",
                    models.UUIDField(
                        blank=True, db_index=True, verbose_name="Промокод"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=catalog.models.sale_product_directory_path,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "date_start",
                    models.DateField(
                        blank=True, db_index=True, verbose_name="Дата начала"
                    ),
                ),
                (
                    "date_end",
                    models.DateField(
                        blank=True, db_index=True, verbose_name="Дата конца"
                    ),
                ),
                (
                    "stocks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sales",
                        to="catalog.stock",
                        verbose_name="Склады",
                    ),
                ),
            ],
            options={
                "verbose_name": "Скидка",
                "verbose_name_plural": "Скидки",
            },
        ),
    ]
