# Generated by Django 4.2.2 on 2023-12-19 10:47

from django.db import migrations, models

import catalog.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_alter_stock_product_alter_stock_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="characteristics",
            field=models.JSONField(
                blank=True,
                default=catalog.models.get_default_value_for_characteristics,
                null=True,
                verbose_name="Характиристики",
            ),
        ),
    ]
