# Generated by Django 4.2.2 on 2023-12-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_alter_product_characteristics"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="sorted_index",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Индекс сортировки"
            ),
        ),
    ]
