# Generated by Django 4.2.2 on 2023-12-27 10:10

from django.db import migrations, models

import catalog.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_alter_product_characteristics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=catalog.models.banner_image_directory_path,
                verbose_name="Изображение",
            ),
        ),
    ]
