# Generated by Django 4.2.2 on 2023-12-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_category_sorted_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleproduct",
            name="sale_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Размер скидки"),
        ),
        migrations.AddField(
            model_name="saleproduct",
            name="sale_type",
            field=models.CharField(
                choices=[("percent", "Percent"), ("ruble", "Ruble")],
                default="percent",
                max_length=10,
                verbose_name="Тип скидки",
            ),
        ),
    ]
