# Generated by Django 4.2.2 on 2023-12-27 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_alter_banner_image"),
        ("catalog", "0010_saleproduct_sale_count_saleproduct_sale_type"),
    ]

    operations = []
