# Generated by Django 4.2.2 on 2023-12-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_merge_20231227_1041"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleproduct",
            name="promocode",
            field=models.UUIDField(
                blank=True, db_index=True, unique=True, verbose_name="Промокод"
            ),
        ),
    ]
