# Generated by Django 4.2.2 on 2023-10-21 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0002_initial"),
        ("catalog", "0004_alter_review_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_address", models.TextField(verbose_name="delivery address")),
                (
                    "comment",
                    models.TextField(
                        blank=True, default="No comment", verbose_name="comment"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=16, verbose_name="price"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="created date"
                    ),
                ),
                (
                    "delivery_method",
                    models.TextField(
                        choices=[
                            ("DELIVERY", "Доставка"),
                            ("EXPRESS_DELIVERY", "Экспресс доставка"),
                        ],
                        default="DELIVERY",
                        verbose_name="delivery method",
                    ),
                ),
                (
                    "payment_method",
                    models.TextField(
                        choices=[
                            ("CARD", "Онлайн картой"),
                            ("SOMEONE_ACCOUNT", "Онлайн с чужого счета"),
                        ],
                        default="CARD",
                        verbose_name="payment method",
                    ),
                ),
                ("pay_result", models.BooleanField(verbose_name="pay result")),
                (
                    "order_status",
                    models.TextField(
                        choices=[
                            ("NOT_PAID", "Не оплачен"),
                            ("PAID", "Оплачен"),
                            ("IN_DELIVERY", "В доставке"),
                            ("DELIVERED", "Доставлен"),
                        ],
                        default="NOT_PAID",
                        verbose_name="order status",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="account.profile",
                        verbose_name="orders",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.CreateModel(
            name="OrderItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0, verbose_name="count")),
                (
                    "full_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="full price",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="order.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="catalog.stock",
                        verbose_name="stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order item",
                "verbose_name_plural": "Order items",
            },
        ),
    ]
