# Generated by Django 4.2.2 on 2023-11-02 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_profile_options_alter_user_options_and_more"),
        ("catalog", "0005_alter_banner_options_alter_productimage_options_and_more"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Заказ", "verbose_name_plural": "Заказы"},
        ),
        migrations.AlterField(
            model_name="order",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(verbose_name="Адрес доставки"),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_method",
            field=models.TextField(
                choices=[("DELIVERY", "Доставка"), ("EXR", "Экспресс доставка")],
                default="DELIVERY",
                verbose_name="Способ доставки",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.TextField(
                choices=[
                    ("NOT_PAID", "Не оплачен"),
                    ("PAID", "Оплачен"),
                    ("IN_DELIVERY", "В доставке"),
                    ("DELIVERED", "Доставлен"),
                ],
                default="NOT_PAID",
                verbose_name="Статус оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="pay_result",
            field=models.BooleanField(verbose_name="Оплачен"),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.TextField(
                choices=[
                    ("CARD", "Онлайн картой"),
                    ("SOME_ACCOUNT", "Онлайн с чужого счета"),
                ],
                default="CARD",
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=16, verbose_name="Стоимость"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="account.profile",
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="orderitemmodel",
            name="count",
            field=models.PositiveIntegerField(default=0, verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="orderitemmodel",
            name="full_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=16, verbose_name="Сумма"
            ),
        ),
        migrations.AlterField(
            model_name="orderitemmodel",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="order.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AlterField(
            model_name="orderitemmodel",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="catalog.stock",
                verbose_name="Склад",
            ),
        ),
    ]
