# Generated by Django 4.2.2 on 2023-11-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_order_pay_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_error",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=200,
                null=True,
                verbose_name="payment error",
            ),
        ),
    ]
