# Generated by Django 4.2.2 on 2023-11-03 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_order_options_alter_order_comment_and_more"),
        ("order", "0002_alter_order_pay_result"),
    ]

    operations = []
