# Generated by Django 4.2.2 on 2023-11-09 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_order_payment_error"),
        ("order", "0004_alter_order_comment_alter_order_delivery_method_and_more"),
    ]

    operations = []
