# Generated by Django 4.2.2 on 2023-11-02 19:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import account.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_review_rating"),
        ("account", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Профиль", "verbose_name_plural": "Профили"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=account.models.get_profile_avatar_path,
                validators=[account.models.validate_image],
                verbose_name="Аватар",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                max_length=18,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+7 \\(\\d{3}\\) \\d{3}-\\d{2}-\\d{2}$",
                        message="Номер телефона должен быть в формате +7 (999) 999-99-99",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profiles",
                to="catalog.seller",
                verbose_name="Продавец",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="E-mail адрес"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="surname",
            field=models.CharField(blank=True, max_length=150, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=100,
                validators=[account.models.validate_my_field],
                verbose_name="Имя пользователя",
            ),
        ),
    ]
