# Generated by Django 4.2.2 on 2023-12-26 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_profile_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=18,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+7 \\(\\d{3}\\) \\d{3}-\\d{2}-\\d{2}$",
                        message="Номер телефона должен быть в формате +7 (999) 999-99-99",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
    ]
