# Generated by Django 4.2.2 on 2023-10-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cache_active",
                    models.BooleanField(default=False, verbose_name="cache_active"),
                ),
                (
                    "cache_time",
                    models.PositiveIntegerField(
                        default=86400, verbose_name="cache_time"
                    ),
                ),
                (
                    "cache_products_time",
                    models.PositiveIntegerField(
                        default=3600, verbose_name="cache_products_time"
                    ),
                ),
            ],
            options={
                "verbose_name": "SiteSetting",
                "verbose_name_plural": "SiteSettings",
            },
        ),
    ]
