# Generated by Django 4.2.2 on 2023-11-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitesettings",
            options={
                "verbose_name": "Настройки сайта",
                "verbose_name_plural": "Настройки сайта",
            },
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="cache_active",
            field=models.BooleanField(default=False, verbose_name="Активный"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="cache_products_time",
            field=models.PositiveIntegerField(
                default=3600, verbose_name="Время кэша для продуктов"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="cache_time",
            field=models.PositiveIntegerField(default=86400, verbose_name="Время кэша"),
        ),
    ]
