# Generated by Django 4.2.2 on 2023-11-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliverySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_cost_limit",
                    models.PositiveIntegerField(
                        default=2000, verbose_name="order_cost_limit"
                    ),
                ),
                (
                    "delivery_markup",
                    models.PositiveIntegerField(
                        default=200, verbose_name="delivery_markup"
                    ),
                ),
            ],
            options={
                "verbose_name": "DeliverySetting",
                "verbose_name_plural": "DeliverySettings",
            },
        ),
    ]
