# Generated by Django 4.2.2 on 2023-11-09 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_sitesettings_options_and_more"),
        ("core", "0002_deliverysettings"),
    ]

    operations = []
