# Generated by Django 4.2.2 on 2023-12-10 07:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_merge_20231109_1244"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliverysettings",
            options={
                "verbose_name": "Настройки доставки",
                "verbose_name_plural": "Настройки доставки",
            },
        ),
    ]
